### ISSUE TITLE
希望增加一个指定监听端口的参数

### ISSUE THREAD

**Issue by lyd0** [cellbang/malagu#123]
文档： [部署在传统服务器](https://malagu.cellbang.com/cloud/%E4%BC%A0%E7%BB%9F%E6%9C%8D%E5%8A%A1%E5%99%A8)
node index.js之后默认监听9000端口，能否增加一个指定端口的参数？

使用`malagu build -m server` 命令进行build的。

![image](https://user-images.githubusercontent.com/29918052/154226903-44bb2fdc-48f2-49be-af9e-c49634cd48bb.png)

**Comment by muxiangqiu** [comment]
你是希望构建完成后改变简单的端口号吗？

**Comment by muxiangqiu** [comment]
v2.11.5 版本支持环境变量设置端口：`SERVER_PORT`

**Comment by lyd0** [comment]
> v2.11.5 版本支持环境变量设置端口：`SERVER_PORT`

是的，我知道本地运行的时候malagu serve -p 3000可以修改端口，但是构建出来的index.js默认是9000，这个端口我不知道在哪里配置修改。好的 我升级尝试一下环境变量
