### ISSUE TITLE
希望支持编译后通过malagu.yml注入运行参数

### ISSUE THREAD

**Issue by lovezhang511** [cellbang/malagu#143]
配置文件更改运行参数，对于传统服务器部署，或者直接用开发工具类应用很友好。更容易理解如何配置。

**Comment by muxiangqiu** [comment]
提供一个新组件：@malagu/config，用于提供运行时的配置属性方式。没有直接在 @malagu/core 组件中实现的原因是运行时配置属性的实现依赖 js-yaml 和 lodash-mergewith 包，不想让 @malagu/core 依赖过多第三方包。而且运行时配饰属性的功能是可选的，所有拆开成独立的组件。同时也方便未来提供更为强大的配置方式。

目前，包含以下运行时配置属性策略：

1. 通过环境变量 MALAGU_PROPS_FILE 配置属性文件位置；
2. 尝试从 `process.cwd()` 和 `__dirname` 目录下加载 malagu.yml 和 malagu.yaml 配置文件

**Comment by muxiangqiu** [comment]
2.24.0 已提供该功能
