### ISSUE TITLE
升级 webpack 版本到 5.x.x

### ISSUE THREAD

**Issue by muxiangqiu** [cellbang/malagu#15]

**Comment by lzy2014love** [comment]
1. 找出所有 webpack 的 loader 和 plugin， 看是否都支持 webpack5，如果不支持是否有替代或者可以简单改造即可
2. webpack的顶级第三方插件如 babel，postcss 等生态的插件是否跟上 webpack5 的支持
3. webpack5 有哪些 break changes ，malagu 项目有哪些地方会使用到

**Comment by wulinsheng123** [comment]
https://github.com/xccjk/x-blog/issues/26
webpack升级过程问题记录文章

**Comment by wulinsheng123** [comment]
**找出所有 webpack 的 loader 和 plugin， 看是否都支持 webpack5，如果不支持是否有替代或者可以简单改造即可**
- [x] /dev-package/cli
- [x] /dev-package/cli-common
- [x] /dev-package/compression

- compression-webpack-plugin **以支持**
