### ISSUE TITLE
支持pnpm项目

### ISSUE THREAD

**Issue by bingtsingw** [cellbang/malagu#153]
#154 目前写了一部分

TODO:
1. [x] zip打包要支持 `symlinks`
2. [x] `Pnpm.ts` 中 `rebaseLockfile` 函数没有实际功能
3. [x] 检查`cli/init/init-manager.ts` 中有关Packager的逻辑
4. [x] 检查 `cli/update/update.ts` 中有关Packager的逻辑

**Comment by bingtsingw** [comment]
关于第二点, 我不太清楚`rebase`具体是干嘛的, 但是直接把`pnpm-lock.yaml`复制到`dist`里也能正常运行

**Comment by bingtsingw** [comment]
关于第三点, 源代码如下
```typescript
async install(): Promise<void> {
    const pkg = CommandUtil.getPkg(undefined, this.outputDir);
    await getPackager(pkg.rootComponentPackage.malaguComponent?.packager, this.outputDir).install({}, this.outputDir);
}
```

但是在用户执行命令`malagu init`的时候, `pkg.rootComponentPackage.malaguComponent?.packager`的值应该都是空的, 这段代码实际没有效果, 所以建议在`init`的时候, 让用户选择`packager`, 不知道是否可行

**Comment by bingtsingw** [comment]
关于第四点, 源码里写死了`npm`, 应该连`yarn`都不支持, 不知道是不是远古bug
```typescript
await getPackager('npm').add([`${pkg.name}@${latest}`], { global: true });
```

好像把`npm`删掉就能自动支持`yarn`和`pnpm`了

**Comment by muxiangqiu** [comment]
> 关于第三点, 源代码如下
> 
> ```ts
> async install(): Promise<void> {
>     const pkg = CommandUtil.getPkg(undefined, this.outputDir);
>     await getPackager(pkg.rootComponentPackage.malaguComponent?.packager, this.outputDir).install({}, this.outputDir);
> }
> ```
> 
> 但是在用户执行命令`malagu init`的时候, `pkg.rootComponentPackage.malaguComponent?.packager`的值应该都是空的, 这段代码实际没有效果, 所以建议在`init`的时候, 让用户选择`packager`, 不知道是否可行

1. malagu init 的时候可能不为空，模板里面可能会定义该属性
2. 当该属性为空时，malagu 的做法是检查项目根目录下的 lock 文件类型来判断基于什么工具安装依赖
3. 如果也不存在 lock 文件，无法判断，则是有 yarn 用 yarn，无 yarn，就用  npm

这是目前的逻辑，你可以思考一下，在上面条件都不满足的情况下，是让用户自己选好，还是帮用户默认选择一个好。

**Comment by muxiangqiu** [comment]
> 关于第四点, 源码里写死了`npm`, 应该连`yarn`都不支持, 不知道是不是远古bug
> 
> ```ts
> await getPackager('npm').add([`${pkg.name}@${latest}`], { global: true });
> ```
> 
> 好像把`npm`删掉就能自动支持`yarn`和`pnpm`了

这里安装的是运行时的依赖包，安装在一个全局的位置，所有必须要固定安装工具类型，不然 lock 文件乱了。所以这里用 npm 更合适些

**Comment by bingtsingw** [comment]
> > 关于第三点, 源代码如下
> > ```ts
> > async install(): Promise<void> {
> >     const pkg = CommandUtil.getPkg(undefined, this.outputDir);
> >     await getPackager(pkg.rootComponentPackage.malaguComponent?.packager, this.outputDir).install({}, this.outputDir);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是在用户执行命令`malagu init`的时候, `pkg.rootComponentPackage.malaguComponent?.packager`的值应该都是空的, 这段代码实际没有效果, 所以建议在`init`的时候, 让用户选择`packager`, 不知道是否可行
> 
> 1. malagu init 的时候可能不为空，模板里面可能会定义该属性
> 2. 当该属性为空时，malagu 的做法是检查项目根目录下的 lock 文件类型来判断基于什么工具安装依赖
> 3. 如果也不存在 lock 文件，无法判断，则是有 yarn 用 yarn，无 yarn，就用  npm
> 
> 这是目前的逻辑，你可以思考一下，在上面条件都不满足的情况下，是让用户自己选好，还是帮用户默认选择一个好。

init不是创建新项目吗, 还会有根据根目录判断吗.

**Comment by bingtsingw** [comment]
> > 关于第二点, 我不太清楚`rebase`具体是干嘛的, 但是直接把`pnpm-lock.yaml`复制到`dist`里也能正常运行
> 
> 项目构建打包的时候，会在构建输出中生成真正的 package.json，基于新的 package.json 文件重新安装以来。为了保证重新安装的依赖版本与开发时安装的版本一致，会通过 rebaseLockfile 把根目录的 lock 文件复制一份到构建输出目录。复制的过程中可能还会做一些额外转换：比如一些相对路径在移动以后，可能就不正确了，需要做简单修正。

好像是和[安装本地package](https://github.com/serverless-heaven/serverless-webpack/commit/c4a1a698501a6b5b64906b18d03f041a4c816ca7)有关, 感觉场景有限, 暂时可以不加.
