### ISSUE TITLE
【文档完善】补充一个多环境隔离原理图

### ISSUE THREAD

**Issue by muxiangqiu** [cellbang/malagu#4]
背景：未来保证项目的质量，一般会有多套运行环境，一般三套：测试、预发和线上。测试环境主要给开发人员测试验证用的，数据库一般是测试数据库；预发环境是一个非常接近线上的一个环境，预发验证没有问题后，就可以发布到线上环境了。

Malagu 框架通过组件属性的覆盖和运行模式，以及对 el 表达式支持，能够很容易做到多环境的隔离部署。

**Comment by seajean** [comment]
目前对malaghu deloy配置的解释和原理都不够详细~

**Comment by 2234839** [comment]
@muxiangqiu 这里的多环境具体指哪方面的？

**Comment by muxiangqiu** [comment]
> @muxiangqiu 这里的多环境具体指哪方面的？

@2234839 补充了一下描述

**Comment by 2234839** [comment]
https://www.yuque.com/cellbang/malagu/urdp03 已补充 https://excalidraw.com/#json=4865938008571904,f9SmzTrjsffBXe5pdUlPUg
