### ISSUE TITLE
配置文件动态更新

### ISSUE THREAD

**Issue by lccf** [cellbang/malagu#44]
### 场景

开发过程中一些针对业务的配置经常需要修改调试，当前配置文件在服务启动后无法更新，需要手动重启。

### 方案参考
- 1.为配置模块添加hook，可以在代码中动态修改配置，通过代码的热更实现配置更新。开发时将需要频繁调整的配置集成在代码中，发布前迁移到yml文件中。
- 2.侦测yml文件的更新，利用webpack的hmr动态更新配置。
- 3.开发模式侦测到yml文件变更后自动重启当前服务。

说明：方案1实现相对简单，可满足场景需求。方案2体验好，实现复杂。方案3体验差。

**Comment by muxiangqiu** [comment]
初步判断下来只能安装方案 3 实现，好像做不到 HMR，应为属性的生命周期比 HMR 长
