### ISSUE TITLE
访问deploy发布之后的页面，没有展示正常的页面，而是下载了一个html

### ISSUE THREAD

**Issue by lxin131** [cellbang/malagu#48]
使用admin-app模板，阿里云FC，deploy之后生成的链接在浏览器里面访问，直接下载了一个html，预期是能够在浏览器里面看到页面

**Comment by 2234839** [comment]
> 使用admin-app模板，阿里云FC，deploy之后生成的链接在浏览器里面访问，直接下载了一个html，预期是能够在浏览器里面看到页面

这是阿里云的设置，需要设置一个域名
