### ISSUE TITLE
malagu cli 目前需要改进的点

### ISSUE THREAD

**Issue by lzy2014love** [cellbang/malagu#78]
1. 对于命令 malagu -v， malagu -h 也需要 load cli context，需要等一点时间才能看到结果
2. 对于不支持的框架使用 malagu deploy 命令，提示Unknown command deploy, 可以增加  malagu support list，malagu support 查看malagu 支持的框架和检测当前项目是否支持 malagu 部署
3. 对于部署在 scf web 函数的用户， 要提醒或者文档显眼说明注意点。
>   - 只能监听 9000 固定端口和地址 0.0.0.0
>   - 只有 /tmp 目录可读可写， 读写其他目录文件不没有权限
4. 增加命令 malagu deploy -c 或者 malagu deploy -config 指定部署配置，可以是json 文件和 js 文件（这两种前端项目比较常用），配置项可以有 部署平台， 部署模式， 自定义支持框架，添加环境变量 等。

**Comment by muxiangqiu** [comment]
1. 必须要加载 context，因为 malagu 的命令是根据环境动态扩展的，看看有没有可能优化一下 context 加载的速度
2. deploy 命令是一个扩展命令，没有 deploy 命令也是一种正常的行为，框架层面做这种检测没有必要，可以让框架使用者去判断，malagu support list => malagu framework list，这样好些，框架是可选的，不是必选，不支持的框架也是可以使用 malagu 部署的
3. /tmp 的是 Serverless 平台带来的问题，额外再提醒一下使用者也没啥问题，具体还是要看具体平台的限制
4. 如果要加 --config 选项，所有命令都需要支持 config，这个可以考虑，json 和 js 形式的配置，我还没有想清楚，主要是 malagu 属性风格不太适合 json 格式，js 方式对我们的打包会带来破坏性，过多的配置形式，会带来混乱，文档负担，加载变慢等等。

**Comment by lzy2014love** [comment]
对于 1， 2 点 我去改进下。 4点再一起思考多点场景再改进

**Comment by muxiangqiu** [comment]
第 4 点，我已经提供了 ‘malagu props’ 命令，如下：
```bash
                   ___
 /'\_/`\          /\_ \
/\      \     __  \//\ \      __       __   __  __
\ \ \__\ \  /'__`\  \ \ \   /'__`\   /'_ `\/\ \/\ \
 \ \ \_/\ \/\ \L\.\_ \_\ \_/\ \L\.\_/\ \L\ \ \ \_\ \
  \ \_\\ \_\ \__/.\_\/\____\ \__/.\_\ \____ \ \____/
   \/_/ \/_/\/__/\/_/\/____/\/__/\/_/\/___L\ \/___/
                                       /\____/
                   @malagu/cli@2.5.10  \_/__/

╭──────────────────────────────────────────────────╮
│      Serverless Frist Development Framework      │
│                  Runtime<vite>                   │
╰──────────────────────────────────────────────────╯

Usage: malagu props [options]

display properties about application

Options:
  -n, --name [name]          get the property value of the specified name
  -f, --frontend [frontend]  frontend properties
  -b, --backend [backend]        backend properties
  -h, --help                 display help for command
```
