### ISSUE TITLE
npm run build 有报错信息但build成功

### ISSUE THREAD

**Issue by lzy2014love** [cellbang/malagu#9]
![image](https://user-images.githubusercontent.com/23011780/107107323-57471e00-686b-11eb-8834-f67075fe5980.png)
环境： windows7 nodejs@12.16.1 模版: site

**Comment by muxiangqiu** [comment]
malagu 项目编译的时候用到了 hard source webpack 插件，主要作用是缓存编译过且为改变的模块，从而提升编译速度。这里有个官方 [issue](https://github.com/mzgoddard/hard-source-webpack-plugin/pull/419)。

解决方案：删掉 node_modules 下面的 .cache 目录就好了。

**Comment by lzy2014love** [comment]
解决了
