### ISSUE TITLE
升级存在安全漏洞的依赖版本

### ISSUE THREAD

**Issue by muxiangqiu** [cellbang/malagu#94]

**Comment by muxiangqiu** [comment]
![image](https://user-images.githubusercontent.com/11471925/149313354-e62beab9-b389-4bdc-9153-ad3b00a422c3.png)

**Comment by JarynChen** [comment]
## 更新依赖统计

### follow-redirects
- 当前危险等级: high severity
- 最新版本: 1.14.7
- 最低安全版本: 1.14.7
- 最后更新时间: 4天前
- 更新状态: 维护中
- 项目依赖情况
```
authing-js-sdk@4.23.13 -> axios@0.19.2 -> "follow-redirects": "1.5.10"
```
> authing-js-sdk
> 最新版: 4.23.13
> 更新时间: 16 hours ago
> 备注:
> 无相关issue, 有axios版本升级pr,未合并
> https://github.com/Authing/authing.js/pull/84

```
axios@0.24.0 -> "follow-redirects": "^1.14.4"
```
> axios
> 最新版: 0.24.0
> 更新时间: 3 months ago
> 备注: 
> 已有pr升级该依赖版本, 待发布新版本
> https://github.com/axios/axios/pull/4379

```
http-proxy@1.18.1 -> "follow-redirects": "^1.0.0"
```
> http-proxy
> 最新版: 1.18.1
> 更新时间: 2 years ago
> 备注:
> 已有pr升级该依赖版本, 未合并, 未发布新版本, 官方大概放弃了
> https://github.com/http-party/node-http-proxy/pull/1564


### node-forge
- 当前危险等级: low severity
- 最新版本: 1.2.1
- 最低安全版本: 1.0.0
- 最后更新时间: 2天前
- 更新状态: 维护中
- 项目依赖情况
```
selfsigned@2.0.0 -> "node-forge": "^1.2.0"
```
> selfsigned
> 最新版: 2.0.0
> 更新时间: 3 days ago


### json-schema
- 当前危险等级: moderate severity
- 最新版本: 0.4.0
- 最低安全版本: 0.4.0
- 最后更新时间: 2个月前
- 更新状态: 未知
- 项目依赖情况
```
jsprim@1.4.2 -> "json-schema": "0.4.0"
```

```
workbox-build@6.4.2 -> @apideck/better-ajv-errors@0.3.2 -> "json-schema": "^0.4.0"
```

```
minipass-sized@1.0.3 -> "json-schema": "0.2.3"
```
> minipass-sized
> 最新版: 1.0.3
> 更新时间: 2 years ago
> 备注:
> 无issue, 无pr
```
npm-normalize-package-bin@1.0.1 -> "json-schema": "0.2.3"
```
> npm-normalize-package-bin
> 最新版: 1.0.1
> 更新时间: 2 years ago
> 备注:
> 无issue, 无pr

### validator
- 当前危险等级: moderate severity
- 最新版本: 13.7.0
- 最低安全版本: 13.7.0
- 最后更新时间: 2个月前
- 更新状态: 维护中
- 项目依赖情况
```
class-validator@0.13.2 -> "validator": "^13.7.0"
```


### class-validator
- 当前危险等级: moderate severity
- 最新版本: 0.13.2
- 最低安全版本: 0.13.1
- 最后更新时间: 2个月前
- 更新状态: 维护中
- 项目依赖情况
```
@malagu/web@2.8.9 -> "class-validator": "^0.13.1"
```

### ansi-regex
- 当前危险等级: moderate severity
- 最新版本: 6.0.1
- 最低安全版本: 6.0.1
- 最后更新时间: 4个月前
- 更新状态: 未知
- 项目依赖情况
> 这个依赖有点多

### nth-check
- 当前危险等级: moderate severity
- 最新版本: 2.0.1
- 最低安全版本: 2.0.1
- 最后更新时间: 4个月前
- 更新状态: 未知
- 项目依赖情况
```
css-select@4.2.1 -> "nth-check": "^2.0.1"
```

```
svgo@1.3.2 -> css-select@2.1.0 -> "nth-check": "^1.0.2"
```
> svgo
> 最新版: 2.8.0
> 更新时间: 2 months ago
> 备注: 
> 可更新, 需关注breaking change

### pac-resolver
- 当前危险等级: high severity
- 最新版本: 5.0.0
- 最低安全版本: 5.0.0
- 最后更新时间: 6个月前
- 更新状态: 未知
- 项目依赖情况
```
pac-proxy-agent@5.0.0 -> "pac-resolver": "^5.0.0"
```

### normalize-url
- 当前危险等级: high severity
- 最新版本: 7.0.2
- 最低安全版本: 4.5.1
- 最后更新时间: 7个月前
- 更新状态: 未知
- 项目依赖情况
```
parse-url@6.0.0 -> "normalize-url": "^6.1.0"
```
```
cacheable-request@7.0.2 -> "normalize-url": "^6.0.1"
```
```
postcss-normalize-url@5.0.4 -> "normalize-url": "^6.0.1"
```
```
cacheable-request@6.1.0 -> "normalize-url": "^4.1.0"
```
> cacheable-request
> 最新版: 7.0.2
> 更新时间: 7 months ago
> 备注:
> 可更新, 需关注breaking change
```
postcss-normalize-url@4.0.1 -> "normalize-url": "^3.0.0"
```
> postcss-normalize-url
> 最新版: 5.0.4
> 更新时间: a month ago


### postcss
- 当前危险等级: moderate severity
- 最新版本: 8.4.5
- 最低安全版本: 8.2.13
- 最后更新时间: 1个月前
- 更新状态: 维护中
- 项目依赖情况
> 这个依赖有点多


### css-what
- 当前危险等级: high severity
- 最新版本: 6.0.1
- 最低安全版本: 5.0.1
- 最后更新时间: 18天前
- 更新状态: 维护中
- 项目依赖情况
```
css-select@4.2.1 -> "css-what": "^5.1.0"
```
```
svgo@1.3.2 -> css-select@2.1.0 -> "css-what": "^3.2.1"
```
> svgo
> 最新版: 2.8.0
> 更新时间: 2 months ago
> 备注: 
> 可更新, 需关注breaking change

### ws
- 当前危险等级: moderate severity
- 最新版本: 8.4.1
- 最低安全版本: 7.4.6
- 最后更新时间: 13小时前
- 更新状态: 维护中
- 项目依赖情况
> 这个依赖有点多

### dns-packet
- 当前危险等级: high severity
- 最新版本: 5.3.1
- 最低安全版本: 1.3.2
- 最后更新时间: 22天前
- 更新状态: 维护中
- 项目依赖情况
```
multicast-dns@6.2.3 -> "dns-packet": "^1.3.1"
```
> multicast-dns
> 最新版: 7.2.4
> 更新时间: 3 months ago
> 备注: 
> 可更新, 需关注breaking change

### axios
- 当前危险等级: high severity
- 最新版本: 0.24.0
- 最低安全版本: 0.21.2
- 最后更新时间: 3个月前
- 更新状态: 维护中
- 项目依赖情况
> 这个依赖有点多

**Comment by JarynChen** [comment]
## 更新计划

### 忽略(无需)升级
- node-forge
- validator
- class-validator
- pac-resolver

### 无法升级
- follow-redirects
- json-schema

### 需升级
- nth-check
- normalize-url
- css-what
- dns-packet

### 待确定
- ansi-regex
- postcss
- ws
- axios
